---
- name: My First playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install package
    package:
      name: httpd
      state: installed 

  - name: Install Telnet
    package:
      name: telnet
      state: installed 

  - name: Add Bob
    user:
      name: httpd
      state: absent 

  - name: Add Tom
    user:
      name: tom
<<<<<<< HEAD
      state: present
=======
      state: present
>>>>>>> 682f20b8f54a3166759d95740a896b57c4623bfa
