---
- name: Task playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install package
    package:
      name: httpd
      state: installed 

  - name: Install Worpress
    package:
      name: wordpress
      state: installed 

  - name: Add Bob
    user:
      name: httpd
      state: absent 

  - name: Add Tom
    user:
      name: tom
      state: present